### ISSUE TITLE
增加 PHP 版本支援

### ISSUE THREAD

**Issue by johnroyer** [johnroyer/php-easy-container#2]
目前這個工具沒有複雜到一定需要 PHP 7.1 才能執行，請協助移除部份 PHP 7.x 的 feature，使程式碼也可以在 PHP 5.6 執行。

**Comment by johnroyer** [comment]
@passionFarmer64 請你參考 [PHP 7 features](http://php.net/manual/en/migration70.new-features.php) 以及 PHP 7.1 的 changelog，嘗試找出哪些非必要的語法，並將其移除，使 `/src/Container.php` 可以在 PHP 5.6 下正常運作。

ps. 我已經寫好 test case，在專案根目錄執行 `vendor/bin/phpunit` 即可自動執行測試，並藉由測試結果判斷是否可以正常執行。有其他問題請發問，別客氣～

**Comment by passionFarmer64** [comment]
要使用 composer.json 裡面記載的 phpunit/phpunit 版本  
於 php ^5.6 就出現不合的版本了耶  
這個也是算在相容性調整的範圍內嗎?  
>  - phpunit/phpunit 6.0.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement

**Comment by johnroyer** [comment]
是喔，一起調整吧～

你都在上班玩這個嗎  XD

**Comment by passionFarmer64** [comment]
這邊都是開放的 repo 耶... 不能說太多  
只能說公司的工具環境比較齊全 XD

**Comment by passionFarmer64** [comment]
看你程式 Container.php 裡面的 function 都有註解回傳值等資訊，這個你是自已手建的還是有程式可以自動建立啊?

**Comment by johnroyer** [comment]
看來你有注意到了， PHP 7.0 以後支援使用 primitive type 來做 type hint，像是 `int`、`float` 等，但是舊版的則沒辦法。

在 PHP 還不支援 primitive type hinting 的時候，大概只有二種方法：

- 使用 [doc comment](https://docs.phpdoc.org/references/phpdoc/tags/param.html) 的方式告訴使用者傳入、輸出的參數應該是什麼資料型態
- 把 primitive type 封裝成一個物件來傳遞 (像是 SPL data type: [DateTime](http://php.net/manual/en/class.datetime.php))

----

記得我有寫 doc comment，所以把 type hinting 拔掉應該沒啥問題

**Comment by passionFarmer64** [comment]
已 merge  
界面跟你架的網站好像有點不一樣  
不知道有沒有成功  
再請你確認一下囉  :blush:

**Comment by passionFarmer64** [comment]
travis ci 可以跟 github 作結合  
那他可以跟個人架的 git 網站結合嗎?  
有些程式不方便放在官方 github 上，但也不想付費取得 private 功能 XD

**Comment by johnroyer** [comment]
可以，不過要收費

https://travis-ci.com/plans

**Comment by johnroyer** [comment]
done
